### ISSUE TITLE
Separate unwanted firestore fields from data

### ISSUE THREAD

**Issue by rolznz** [nandorojo/swr-firestore#103]
Hi, when retrieving data from firestore (`useDocument`, `getDocument` etc), the firestore fields are returned as part of the data (`id`, `exists`, `hasPendingWrites` etc).

This causes multiple issues especially when diffing local models against what is returned from firestore. I either need to manually remove these fields, or (more reliably) pick the specific fields I want into a new object.

Also when retrieving an object using getDocument function I have to do something like:
`const userDoc = await getDocument<IUser & Document>(userPath);` because my user type does not have the fields (I don't want them either so I am not going to make my interface extend from Document).

An easy way to implement this could be to add a `rawData` prop to `useDocument`, and add an `ignoreFirestoreDocumentFields` option to `getDocument` (but the return typings would also need to be changed)

**Comment by nandorojo** [comment]
Yeah I hear you. Unfortunately these would be breaking changes, but I can consider it if I release a major version change. For now I'd extract the fields manually.

**Comment by rolznz** [comment]
@nandorojo thanks for the reply. Should the wrapper function just delete these fields, or do I actually need to pick my own properties into a new object? Can we guarantee that no new firestore fields will be added to minor versions of swr-firestore?

**Comment by nandorojo** [comment]
I would clone the object and omit the fields.

And it's a safe bet to assume we won't add more meta fields, but if we do it won't be hard to edit the wrapper.

**Comment by rolznz** [comment]
Thanks, I will do that to ensure my writes are safe.
