### ISSUE TITLE
Firestore / SWR local persistence

### ISSUE THREAD

**Issue by rolznz** [nandorojo/swr-firestore#104]
Do I need to manually call firebase.firestore().enablePersistence() (I searched for it in the source but can't see anything)? I often see that data is not available after a page refresh.

I know swr-firestore has its own caching mechanisms, is there any downside of enabling firestore persistence?

**Comment by nandorojo** [comment]
This library doesn't do anything related to persistence, it just calls firestore. So as far as I know, as long as you enable persistence the way you would with Firestore, it should work as is.

**Comment by rolznz** [comment]
Thanks!
