### ISSUE TITLE
`useCollection` does not fetch on mount

### ISSUE THREAD

**Issue by sarimabbas** [nandorojo/swr-firestore#110]
Hello, thank you for this lib!
 
I am running into some strange behavior where `useCollection` returns an empty array on mount (but fetches successfully on subsequent renders or when calling `revalidate`). 

My dependencies:

```
    "firebase": "^8.3.2",
    "@nandorojo/swr-firestore": "^0.16.0",
```

My code: 

```ts
const Sidebar = () => {

  const uid = fuego.auth().currentUser?.uid;

  const { data: folders, revalidate } = useCollection<Folder>(
    !!uid ? "folders" : null,
    {
      where: ["userId", "==", uid],
    }
  );

  // revalidating after mount seems to work
  // useEffect(() => {
  //   setTimeout(() => {
  //     revalidate();
  //   }, 2000);
  // }, [uid]);


   return <FolderTree folders={folders}/>
}

```

I would appreciate any insight or help in this matter. Thank you!

**Comment by nandorojo** [comment]
Weird, could you reproduce on codesandbox?

**Comment by sarimabbas** [comment]
I have tried but not been able to produce deterministically on CodeSandbox. I am using a workaround where I revalidate after mount and that seems to work fine. So I will close this issue for now. Thank you for your help!

**Comment by 345ml** [comment]
> I have tried but not been able to produce deterministically on CodeSandbox. I am using a workaround where I revalidate after mount and that seems to work fine. So I will close this issue for now. Thank you for your help!

@sarimabbas 
I can't get the data to refresh on Android, did it work in your environment?
