### ISSUE TITLE
Type error when passing `listen: true` to `useCollectionGroup` query object

### ISSUE THREAD

**Issue by armouti** [nandorojo/swr-firestore#119]
Typescript complains that the `listen: boolean` property does not exist on `useCollectionGroup` query object

<img width="801" alt="Screenshot 2021-05-18 at 06 02 45" src="https://user-images.githubusercontent.com/37476568/118592969-d0291080-b79e-11eb-9d78-0d67b22b8283.png">

**Comment by nandorojo** [comment]
Prefer the `isCollectionGroup` Boolean on `useCollection`
