### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by LucasEduardoGoncalves** [nandorojo/swr-firestore#128]
![image](https://user-images.githubusercontent.com/79141932/130298129-55f3cdb3-840a-4e0e-a2b9-a13bf9d39118.png)

**Comment by alexeyvakarchuk** [comment]
Same error

**Comment by alexeyvakarchuk** [comment]
@LucasEduardoGoncalves @nandorojo I solved it by forking repo and replacing
`import * as firebase from 'firebase/app'`
to 
`import firebase from 'firebase/app'`


at **/swr-firestore/src/classes/Fuego.ts**

**Comment by nandorojo** [comment]
Solution is in the docs for firestore v8.

https://github.com/nandorojo/swr-firestore/issues/59#issuecomment-719950071

**Comment by huy-lv** [comment]
I got this error again on     
```
"expo": "~46.0.7",
"@nandorojo/swr-firestore": "^0.16.0",
"firebase": "9.6.11",
```
