### ISSUE TITLE
Is `useCollection` passing along request.auth to Firestore?

### ISSUE THREAD

**Issue by joed1rk** [nandorojo/swr-firestore#14]
Hi @nandorojo,

I've got a curious situation. 

I'm getting unnecessary permissions error trying to read from a subcollection of my `users` collection.

My Firestore database rules are set to allow reads on any subcollection of collection `users` IF
`request.auth.uid == resource.data.createdBy;`

Rule
```
match /users/{document=**} {
      allow read: if request.auth.uid == resource.data.createdBy;
...
}
```

```useDocument(`users/${userId}`)```
Works fine.

However this does not:
```useCollection(`users/${userId}/subcollection/{someID}`)```

It Throws `FirebaseError: Missing or insufficient permissions.`

So I'm wondering if perhaps useCollection is *not* passing along the request.auth to the firebase request for some reason?

Cheers

**Comment by nandorojo** [comment]
Hey, that seems like it’s an error with the permissions side, not the library. useCollection and useDocument use the same instance of Firebase. 

I’m not an expert in permissions, but I think you need to specify that you can also get access to subcollections that match that pattern (see Firestore docs: https://firebase.google.com/docs/firestore/security/rules-structure#hierarchical_data)

**Comment by nandorojo** [comment]
Ah, looks like you have wildcard permissions set up. That’s odd. It’s hard for me to say. Could you try querying Firestore directly for that document in a `useEffect` and see if you get the same permissions error?

**Comment by nandorojo** [comment]
Try this:

```js
import { fuego } from 'swr-firestore'

export default function Screen() {
  useEffect(() => {
    // check your current uid
    console.log({ uid: fuego.auth().currentUser?.uid })

    // make the request
    fuego.db
      .doc(`users/${userId}/subcollection/{someID}`)
      .get()
      .then((doc) => console.log('doc worked!', doc.id))
  }, [])
}
```

And see if that gives you permissions errors.

**Comment by joed1rk** [comment]
Thanks for the quick reply, let me try this and get back to you.

Very much appreciate your help!

**Comment by joed1rk** [comment]
Ok I tried it:

*this Works*
```javascript
 useEffect(() => {
    fuego.db
      .doc(`users/${userId}/subcollection/${docId}`)
      .get()
      .then((docs) => console.log('doc worked!', doc))
      .catch((e) => console.log(e))
  }, [])```

*This Fails*
```javascript
 useEffect(() => {
    fuego.db
      .collection(`users/${userId}/subcollection`)
      .get()
      .then((docs) => console.log('collection worked!', docs))
      .catch((e) => console.log(e))
  }, [])```

**Comment by nandorojo** [comment]
Got it, seems like it’s a problem with your permissions for getting a collection then?

**Comment by joed1rk** [comment]
I must be misunderstand the Wildcard. Going to read :)

**Comment by joed1rk** [comment]
Thanks again mate, you're grand

**Comment by nandorojo** [comment]
You got it! Going to close this out.
