### ISSUE TITLE
Add Firestore ref to useDocument and useCollection.

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/swr-firestore#16]
# What

It would be useful to be able to access the original Firestore `ref` object for each document.

**For documents:**

```js
const { data } = useDocument('users/fernando')

const onPress = () => {
  data?._ref.set({ hasFreeWill: false }, { merge: true })
}
```

**For collections:**

```js
const { data } = useCollection('users')

if (data) {
  data.forEach((document) => {
    document._ref // Firestore ref
  })
}
```

# Why

It's kind of up to the user. Never know when you'll need this.

A good example is paginating: in order to do `startAfter`, you have to pass a document snapshot (see https://github.com/nandorojo/swr-firestore/issues/7#issuecomment-637874552). Could you do this with just the ref?

- It seems not. Maybe instead of `_ref`, or in addition, we also pass the Firestore `_snapshot` object? I'll look into it

# Opt-out

Maybe there could be an API to opt-out:

```js
const { data } = useDocument('user/fernando', { excludeRefField: true })
```

This would be useful if you need the value to be JSON serializable. Not sure if this should be default enabled or not.

**Comment by goleary** [comment]
another reason this would be useful is in the case where you `useCollection` and then want to modify one of the documents returned in that query.

As I understand with `swr-firestore` you would need to separately call `useDocument` in order to get access to `set`. I'm assuming this would pull from the cache and so still be quite performant, but coming from using firestore this is a bit annoying.

**Comment by nandorojo** [comment]
You can also do this for that situation:

```
import { set } from '@nandorojo/swr-firestore'
```

**Comment by goleary** [comment]
Is this the best way to do that?  
```
import { set } from '@nandojo/swr-firestore';
...
const collection = 'users';
const { data } = useCollection<User>(collection);

for(let user of data) {
   set(`${collection}/${user.id}`, {new: false});
}
```
I wish I cold access the ref/path from the document itself but this isn't too bad.

I also would love typechecking to ensure that the field I'm setting is a valid property of `User` in this example.  Using `set` looks like a nice workaround for now but sub optimal for type safety.

**Comment by armouti** [comment]
yep i've actually needed this and had to implement my own hook with onSnapshot, because i needed to access the sub-collection of a document that i retrieved through a collection query (using `where`)

**Comment by armouti** [comment]
Another use case could be to access the sub-collections of documents retrieved through collection queries (using `where`)

**Comment by nandorojo** [comment]
Snapshot is now added.

Use the `ignoreFirestoreDocumentSnapshotField` to `false`.

Docs: https://github.com/nandorojo/swr-firestore#ignorefirestoredocumentsnapshotfield

```js
// include the firestore document snapshots
const { data } = useDocument('users/fernando', {
  ignoreFirestoreDocumentSnapshotField: false,
})

if (data) {
  const path = data.__snapshot.ref.path
}
```

**Comment by goleary** [comment]
Wonderful, can't wait to try it out!

**Comment by nandorojo** [comment]
This features adds some nice convenience for paginating collections, as seen in the readme [here](https://github.com/nandorojo/swr-firestore/blob/master/README.md#paginate-a-collection).

```jsx
import React from 'react'
import { fuego, useCollection } from '@nandorojo/swr-firestore'

const collection = 'dump'
const limit = 1
const orderBy = 'text'

export default function Paginate() {
  const { data, mutate } = useCollection<{ text: string }>(
    collection,
    {
      limit,
      orderBy,
      // 🚨 this is required to get access to the snapshot!
      ignoreFirestoreDocumentSnapshotField: false
    },
    {
      // this lets us update the local cache + paginate without interruptions
      revalidateOnFocus: false,
      refreshWhenHidden: false,
      refreshWhenOffline: false,
      refreshInterval: 0,
    }
  )

  const paginate = async () => {
    if (!data?.length) return
    
    const ref = fuego.db.collection(collection)
    
    // get the snapshot of last document we have right now in our query
    const startAfterDocument = data[data.length - 1].__snapshot

    // get more documents, after the most recent one we have
    const moreDocs = await ref
      .orderBy(orderBy)
      .startAfter(startAfterDocument)
      .limit(limit)
      .get()
      .then(d => {
        const docs = []
        d.docs.forEach(doc => docs.push({ ...doc.data(), id: doc.id }))
        return docs
      })

    // mutate our local cache, adding the docs we just added
    // set revalidate to false to prevent SWR from revalidating on its own
    mutate(state => [...state, ...moreDocs], false)
  }

  return data ? (
    <div>
      {data.map(({ id, text }) => (
        <div key={id}>{text}</div>
      ))}
      <button onClick={paginate}>paginate</button>
    </div>
  ) : (
    <div>Loading...</div>
  )
}
```
