### ISSUE TITLE
`delete` support

### ISSUE THREAD

**Issue by shunkakinoki** [nandorojo/swr-firestore#18]
Thanks for this AWESOME 🔥🔥🔥 project!!!

At the moment, `set` and `update` seems to be supported, do you have any plans for `delete` support as well?

**Comment by nandorojo** [comment]
Thanks so much for the issue.

Funny enough, I've never found myself using `delete`! I didn't even think to add it. Sure, I'm happy to add it.

**Comment by nandorojo** [comment]
Added in version `0.9.0-alpha.1` with the `@next` tag (https://github.com/nandorojo/swr-firestore/commit/fa4e27961ebbc61fe7ed455cdd2d06e70214d3b3).

```sh
yarn add @nandorojo/swr-firestore@next

# or
npm i @nandorojo/swr-firestore@next
```

Could you test it out and let me know if it works?

**Comment by shunkakinoki** [comment]
Thanks for the awesome work!!! I'm going to try it out immediately 🚀

**Comment by shunkakinoki** [comment]
I've tried it out, the deletion itself works flawlessly 🚀 (THANK YOU!!!)

however, there seems to be a little of delay in the cache 
(to be investigated... may be a problem with my code implementation)

I'll try to put up a reproducible repo by today, if it helps

**Comment by nandorojo** [comment]
Interesting. Yeah if you could reproduce it, would be helpful.

**Comment by nandorojo** [comment]
Just checking on this. Let me know if I should reopen.

**Comment by shunkakinoki** [comment]
I apologize for the late response 
It's working perfectly!  💪
Again, Thanks for the awesome work!!!
