### ISSUE TITLE
[React Native/ Expo only] Add offline support 👀

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/swr-firestore#2]
**This issue only applies to mobile apps built with Expo. Firestore persistence works fine with this library with normal React.**

Data should cache to `AsyncStorage` something like redux persist, and any mutations should somehow bubble up to happen later...🙃

If anyone stumbles upon this, would love help.

**Comment by nandorojo** [comment]
Relevant discussion from SWR: https://github.com/zeit/swr/issues/16

**Comment by puchesjr** [comment]
Wouldn't this be possible by just using the Firestore option of enablePersistence=true?

**Comment by nandorojo** [comment]
Yeah! 

The only problem is that Firestore doesn't have persistence support for `React Native` / @expo, which I use primarily. But if you don't use React Native, then you're fine using the normal Firestore persistence.

**Comment by puchesjr** [comment]
Ah yes - I was thinking of this from a web perspective. But, you could use this https://rnfirebase.io/reference/firestore/settings for react-native :).

**Comment by nandorojo** [comment]
Good call! Unfortunately that library doesn’t support Expo without detaching, so it will only work for Bare expo projects. A pure-JS solution for managed Expo apps specifically is what I’m hoping to achieve

**Comment by nandorojo** [comment]
Solved this with https://github.com/nandorojo/expo-firestore-offline-persistence. Turned it into its own package.
