### ISSUE TITLE
Don’t revalidate for listeners 

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/swr-firestore#20]
Default SWR settings should have no revalidation or polling for listeners.

**Comment by armouti** [comment]
Hey, just wondering if this was closed because it was completed or other reason ?

**Comment by nandorojo** [comment]
@armouti hey, it’s because I added it! I’ll be publishing shortly.

**Comment by armouti** [comment]
sweeet 👌  thanks

**Comment by armouti** [comment]
Hey, any updates on when this might be published :)

**Comment by nandorojo** [comment]
Hey it's published in the `next` version

`yarn add @nandorojo/swr-firestore@next`
