### ISSUE TITLE
update() typings don't accept FieldValues

### ISSUE THREAD

**Issue by dsernst** [nandorojo/swr-firestore#21]
🔥 This library is fantastic! Great work.

Noticed a minor typescript issue:

```tsx
import { useDocument } from '@nandorojo/swr-firestore'
import { useState } from 'react'
import { firestore } from 'firebase'

type Pageviews = { views: number }

export default function ViewCounter() {
  const { data, update, error } = useDocument<Pageviews>(`meta/pageviews`, { listen: true })
  const [incremented, setIncremented] = useState(false)

  if (error) return console.error('error loading page views', error)

  if (data && !incremented) {
    update({ views: firestore.FieldValue.increment(1) })
    setIncremented(true)
  }

  return <p>{data?.views} views</p>
}
```

The line:

```tsx
    update({ views: firestore.FieldValue.increment(1) })
```

throws the typescript error:

```
Type 'FieldValue' is not assignable to type 'number'.  ts(2322)

The expected type comes from property 'views' which is declared here on type 'Partial<Pageviews>'",
```

**Comment by dsernst** [comment]
One manual fix was to adjust the doc's type definition to:

```tsx
type Pageviews = { views: number | firestore.FieldValue }
```

But maybe it would be better to automatically handle this at the library level?

**Comment by nandorojo** [comment]
Hey thanks for the issue. This is a good catch, and an interesting one. I’m not sure how the library would handle this. For the update function, it just passes a `Partial<Data>` field. 

There might be a way to change dynamic number fields in a typescript type to also be firestore field values, but this might require some typescript wizardry. If you have an idea for how that’d be done, I’m happy to add it.

**Comment by dsernst** [comment]
Right. I think this is possible with Generics, similar to this Utility Types library: https://github.com/piotrwitek/utility-types. 

In particular the [FunctionKeys<T>](https://github.com/piotrwitek/utility-types#functionkeyst) one, which extracts properties only if they are functions, could do a similar thing here with numbers.

I'll experiment with it and report back if I get anything working.

**Comment by nandorojo** [comment]
Good call. Yeah, something like this could definitely work:

```typescript 

/**
 * FunctionKeys
 * @desc Get union type of keys that are functions in object type `T`
 * @example
 *  type MixedProps = {name: string; setName: (name: string) => void; someKeys?: string; someFn?: (...args: any) => any;};
 *
 *   // Expect: "setName | someFn"
 *   type Keys = FunctionKeys<MixedProps>;
 */
export type FunctionKeys<T extends object> = {
  [K in keyof T]-?: NonUndefined<T[K]> extends Function ? K : never;
}[keyof T];
```

Let me know if you manage to make it happen!

**Comment by dsernst** [comment]
Check out this brilliant answer to a generic form of this question: https://github.com/pirix-gh/ts-toolbelt/issues/121

There's a one liner, with [`ts-toolbelt`](https://github.com/pirix-gh/ts-toolbelt) as a dependency. Or a dependency-free solution offered as well.

The one aspect that answer is missing — because I wanted to keep it simple — is conditionally only doing this for `number` types. That same author also has a great tutorial [here](https://medium.com/free-code-camp/typescript-curry-ramda-types-f747e99744ab#c714) that explains how to do this sort of conditional, using `extends` and ternaries (search for "Important keywords" section).

On the other hand, the Firestore docs do list [other FieldValue types](https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue). There are array specific ones, but also `FieldValue.delete()` which can be used for any type. So I wonder if it's correct to limit these to only `typeof number`?

Lmk what you think. I'm happy to send a PR to close this issue, or you can take care of it if quicker, whichever you prefer. 🙂

**Comment by nandorojo** [comment]
Very cool. I think it could be smart to have it for all array fields and such, too. But maybe best to start with the numbers, make sure it works, and then we can do the same for the other field types.

If it’s not too much of a hassle, could you share the dependency-free sample here? Thanks so much for the great work here.

**Comment by nandorojo** [comment]
Looking at the issue you shared on TS toolbelt, it looks like the FieldValue would be available for all field types, not just numbers. Unless I’m looking at it incorrectly?

**Comment by dsernst** [comment]
Here's a simple patch to fix this: https://github.com/nandorojo/swr-firestore/pull/29/

I've tested it for my own case, and it works great.

It does allow FieldValues for all types, not just numbers, but I think that's correct because `FieldValue.delete()` could be passed in for any type.

**Comment by nandorojo** [comment]
Looks good to me! I'll test it out and publish. Thanks for the PR!

**Comment by dsernst** [comment]
![](https://media2.giphy.com/media/QU3IYt7FzAYWVJqd2j/giphy.gif?cid=ecf05e47398756de4b8c072807e7c5530c03865dee61308d&rid=giphy.gif)
