### ISSUE TITLE
Something wrong with setup? 

### ISSUE THREAD

**Issue by luddilo** [nandorojo/swr-firestore#23]
I really like the idea of this project, but ran into issues right away. With the following setup code in my nextJS ("next": "9.1.5",) project, I am getting the below error when trying to initialize.

```
import React from 'react'
import App from 'next/app'
import { Fuego, FuegoProvider } from '@nandorojo/swr-firestore'
import prod from "../credentials/prod.json"

const fuego = new Fuego(prod)

class MyApp extends App {
    render() {
        const { Component, pageProps } = this.props
        return (
            <Component {...pageProps} />
        )
    }
}

export default <FuegoProvider fuego={fuego}>{ <MyApp/> }</FuegoProvider>`
```

**"Error: The default export is not a React Component in page: "/_app""**

With the last row changed to: 

`export default function LaApp() {
    return <FuegoProvider fuego={fuego}><MyApp/></FuegoProvider>
  }`

I am instead getting this error: 

**"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."**

Ideas of what could be wrong?

**Comment by nandorojo** [comment]
1. What does your `prod` variable look like? No need for it to be a JSON file. You can write it directly in the page there. It should look like this:

```js
const firebaseConfig = {
  apiKey: 'api-key',
  authDomain: 'project-id.firebaseapp.com',
  databaseURL: 'https://project-id.firebaseio.com',
  projectId: 'project-id',
  storageBucket: 'project-id.appspot.com',
  messagingSenderId: 'sender-id',
  appId: 'app-id',
  measurementId: 'G-measurement-id'
}

const fuego = new Fuego(firebaseConfig)
```

2. It's a little confusing to see what you mean with your code sample. But it should look like this:

```jsx
import React from 'react'
import App from 'next/app'
import { Fuego, FuegoProvider } from '@nandorojo/swr-firestore'

const firebaseConfig = {
  apiKey: 'api-key',
  authDomain: 'project-id.firebaseapp.com',
  databaseURL: 'https://project-id.firebaseio.com',
  projectId: 'project-id',
  storageBucket: 'project-id.appspot.com',
  messagingSenderId: 'sender-id',
  appId: 'app-id',
  measurementId: 'G-measurement-id'
}

const fuego = new Fuego(firebaseConfig)

export default function App({ pageProps, Component }) {
  return (
    <FuegoProvider fuego={fuego}>
      <Component {...pageProps} />
    </FuegoProvider>
  )
}
```
The problem with your example is that you aren't forwarding the `pageProps` and `Component` from your default exported component, which means that the `MyApp` component you made never gets any props. As a result, its `pageProps` and `Component` prop are undefined, providing the error you got.

**Comment by nandorojo** [comment]
@luddilo did you try this?

**Comment by nandorojo** [comment]
Closing this since I haven’t heard back on the proposed solution, let me know if it doesn’t work.
