### ISSUE TITLE
Add collectionGroup query [Feature request]

### ISSUE THREAD

**Issue by Lucas-Geitner** [nandorojo/swr-firestore#27]
Hello, 

Thanks for setting up this great project !

Is the query collectionGroup already in the librairie ? can we help implementing it ? I guess it's not a lots of work, only a duplication of the function useCollection, 

Link to the firebase docs: 

https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

Thanks !

**Comment by nandorojo** [comment]
This isn't added yet but was in the plans. I can take a look at the docs. Are there any major differences from the collection API for querying? If they're similar, we should be able to mostly copy the file for `useCollection`.

**Comment by Lucas-Geitner** [comment]
There is one difference, 
-> all the predicate works: _limit_, _orderBy_
-> The only différence is you need to create an index that supports your collection group query before you use it, like when you have multiple where in a normal collection querie.

Before using a collection group query, you must create an index that supports your collection group query. You can create an index through an error message, the console, or the Firebase CLI.

If you don't create this index before you run your query, you get an error message: 

`Error: 9 FAILED_PRECONDITION: The query requires a COLLECTION_GROUP_ASC index for collection users and field lang. You can create it here: https://console.firebase.google.com/v1/r/project/XXXX/firestore/indexes?create_exemption=XXXX`

**Comment by nandorojo** [comment]
Got it. In that case, from this library's perspective, there is no difference. 

Since there is essentially no API difference, I wonder if the `useCollection` hook should just take a Boolean prop (such as `isCollectionGroup`,) and then a `useCollectionGroup` hook could extend `useCollection` with that set to `true`.

**Comment by Lucas-Geitner** [comment]
Yes good idea !

That's seem's to be a great idea ! 
I'm availlable to test or documented it if needed

**Comment by nandorojo** [comment]
Sounds good, I'll let you know.

**Comment by armouti** [comment]
it's actually "good" to get that error message. it's more of a feature, that link is a direct link to create the exact index you need in your dashboard.
check here:
https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html

**Comment by nandorojo** [comment]
Yup, agreed.

**Comment by nandorojo** [comment]
Hey, I'm working on this now. There are some definite edge cases that have to be worked out for how the cache works.

Right now, SWR cache keys are generated based on a document's path. This path is extracted from the collection path. However, we now need to get the collection path from a document's parent. This presents some challenges for refactoring the cache.

I might release an experimental version to try it out.

**Comment by Lucas-Geitner** [comment]
Awesome ! Thanks for your work, with my team, we would be happy to test and give feedback on this expérimental feature !

**Comment by nandorojo** [comment]
Can you please try `useExperimentalCollectionGroup` published in the latest version?

**Comment by nandorojo** [comment]
Since I haven't heard back on any issues, I'll assume it's been tested in the wild. I'll add `useCollectionGroup` to the next release.
