### ISSUE TITLE
Replace lodash with individual function packages

### ISSUE THREAD

**Issue by praneybehl** [nandorojo/swr-firestore#35]
It's great package by the way. Currently it uses lodash as a dependency and thus imports the whole package 📦, although it just uses get & set methods from lodash.

I've added a PR #34 to fix this. It would help bring the package bundle size by ~60%

Hope it helps.

Cheers!

**Comment by nandorojo** [comment]
Good catch!

**Comment by praneybehl** [comment]
I was looking for a project to contribute to.  Would like to contribute to this project with adding more functionality and tests.
Do you have a code?

**Comment by nandorojo** [comment]
I would say make an issue with any test/functionality you want to add, describing the why/how, and then if we agree it makes sense, submit a PR.
