### ISSUE TITLE
get multiple collection

### ISSUE THREAD

**Issue by deni-rhn** [nandorojo/swr-firestore#36]
hello @nandorojo , thanks for working Great Projects.

But I have questions, can we get multiple collection ?

example:
I have an collection = ['LORM', 'KIND'];
In the same time I will get all data from above collection and grouping in one array, the function look like this :

collection.forEach((item: string) => {
        const { data } = useCollection(`${item}`, { listen: true });
        console.log('data inside map', data);
});

but it not work, can you suggest me the right implementations? 
Thanks

**Comment by armouti** [comment]
@deni-rhn you can't use react hooks in a loop https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

I don't think you could do this using the hooks provided by this lib, I'm not entirely sure though so it'll be good for @nandorojo to chime in

If you want to use useSWR you'd have to implement this fetching logic into the "fetcher" function https://github.com/vercel/swr#api

**Comment by nandorojo** [comment]
@armouti is correct.

Are you sure fetching multiple collections like that is what you actually want to do? What's the real-world use case for that? It's possible the experimental collection group query could solve this for you when it's ready.
