### ISSUE TITLE
Usage of @react-native-firebase/firestore

### ISSUE THREAD

**Issue by goleary** [nandorojo/swr-firestore#39]
I came across your library because I'm looking for something to bridge the gap between usage of firestore in react & in react native.

I see two different packages published on npmjs.com:

- https://www.npmjs.com/package/@nandorojo/swr-firestore (yours @nandorojo)
- https://www.npmjs.com/package/swr-firestore-react-native (by @Lucas-Geitner)

The second one appears to depend on `@react-native-firebase/firestore`.

I have 2 questions:

1. Am I correct in assuming that this library only makes use of the js firebase sdk even when used in react native?
2. @Lucas-Geitner, where is the code hosted for your package?  I see that it has the dependency that I want but see no reference made to it within this repo. (It looks like your package.json still points towards this github repo even though the source seems to differ).

**Comment by nandorojo** [comment]
1. That's correct.
2. I can't help with this one, but if anyone builds a library on top of this, I would expect it to be open source.

I use expo so I'm not familiar w RN Firebase.

Hypothetically, though, you could use any implementation of Firebase with this library. All you'd have to do is extend the `Fuego` class and pass a custom `fuego` variable to the provider.

```tsx
import { CustomFuego } from './custom-fuego'

const fuego = CustomFuego({ ...firebaseConfig })
```

This is what the normal `Fuego` class looks like, so I assume you could replace this with a custom one that uses RN Firebase's import instead of the JS SDK and it would work the same?

```ts
import * as firebase from 'firebase/app'

firebase.initializeApp>[0]

export class Fuego {
  public db: ReturnType<firebase.app.App['firestore']>
  public auth: typeof firebase.auth
  public functions: typeof firebase.functions
  constructor(config: Config) {
    this.db = !firebase.apps.length
      ? firebase.initializeApp(config).firestore()
      : firebase.app().firestore()
    this.auth = firebase.auth
    this.functions = firebase.functions
  }
}

```

**Comment by goleary** [comment]
cool, thanks for the info!

My understanding is that making use of [react-native-firebase](https://rnfirebase.io/) would improve performance over using the js sdk because it makes use of the native sdks instead of doing all work in the render thread.

I wonder if this is precisely what @Lucas-Geitner has done, so I'll wait for him to weigh in.

**Comment by nandorojo** [comment]
I did some looking into `react-native-firebase`.

I think this would work:

```tsx
// App.tsx
import React from 'react'
import { FuegoProvider } from '@nandorojo/swr-firestore'

import firestore from '@react-native-firebase/firestore'

// if you want to use these too...
import auth from '@react-native-firebase/auth'
import functions from '@react-native-firebase/auth'

class CustomFuego {
  public db: ReturnType<typeof firestore>
  public auth: typeof firebase.auth
  public functions: typeof firebase.functions

  constructor() {
    this.db = firestore()
    this.auth = auth
    this.functions = functions
  }
}

const fuego = new CustomFuego(firebaseConfig)

export default function App() {
  return (
    <FuegoProvider fuego={fuego}>
      <YourAppHere />
    </FuegoProvider>
  )
}
```

**Comment by goleary** [comment]
sweet, thanks for digging in! I'll make sure to report back after trying this out.

Feel free to close if you'd like...or perhaps leave open in the interest of this usecase being called out in the readme?

**Comment by nandorojo** [comment]
I can leave it open to see if we get some a substantive answer from people with that use-case. Happy to add to the readme if we do. I might dig into a bare expo app with it too, so I'll see what that's like.

**Comment by Lucas-Geitner** [comment]
Hello everyone,

Sorry for the confusion @goleary, i just wanted to try in production my change before asking for a pull request in @nandorojo project. I'm not really used to open-source and npm package.

I wanted to create a new option to integrate react-native-firebase for this reasons:

1. - Performance reason
2. - I want to use Apple Sign-in which rely on the native driver [auth.AppleAuthProvider.credential](https://rnfirebase.io/auth/social-auth) only available on the native driver. 

[The code is open source here (a fork with only one file changed):
](https://github.com/poesie-io/swr-firestore/blob/use_react_native_firebase/src/classes/Fuego.ts)

With this change, not optimize yet, you can set-up an option initialize  "swr-firestore": `useNativeDriver`. 
If you set useNativeDriver to true, it will load the react-native db, auth and functions...

I would be happy to have your feedback and see how we can merge this

**Comment by nandorojo** [comment]
@Lucas-Geitner thanks for sharing! I'm going to look into react native Firebase and try all this out soon. I wonder if conditionally importing the libraries is needed.

**Comment by henrymoulton** [comment]
After being redirected here from #63 and getting up and running my only complaint is that I have to install `firebase` regardless of using react-native-firebase otherwise I get a bundle error.

**Comment by henrymoulton** [comment]
cc @nandorojo 

@goleary how are you finding it?

**Comment by aimensasi** [comment]
@henrymoulton is right. inside the `classs/Fuego.ts` you are importing the `import * as firebase from 'firebase/app';` which seems to be the source of the problem.


```
error: Error: Unable to resolve module firebase/app from /node_modules/@nandorojo/swr-firestore/src/classes/Fuego.ts: firebase/app could not be found within the project.

> 1 | import * as firebase from 'firebase/app'
```

I followed the instruction above to setup a custom class

```
class CustomFuego {
	public db: ReturnType<typeof firebase.firestore>

	public auth: typeof firebase.auth

	public functions: typeof firebase.functions

	public storage: typeof firebase.storage

	constructor() {
	  this.db = firestore;
	  this.auth = firebase.auth;
	  this.auth = firebase.auth;
	  this.functions = firebase.functions;
	  this.storage = firebase.storage;
	}
}
```

**Comment by nandorojo** [comment]
Maybe you can patch the project to remove that file and its exports.
