### ISSUE TITLE
Usage alongside Firebase Storage

### ISSUE THREAD

**Issue by colinheye** [nandorojo/swr-firestore#41]
I would like to use swr-firestore in an app where I also have downloads from Firebase Storage. Since swr-firestore executes firebase.initializeApp(), is this possible? I will be testing out what happens if I try to add ```import 'firebase/storage'``` to my App component

**Comment by armouti** [comment]
@colinheye yeah you can still use the `firebase` class and methods directly anywhere in your app, but youll have to `import 'firebase/storage'`
