### ISSUE TITLE
Compound queries

### ISSUE THREAD

**Issue by sorxrob** [nandorojo/swr-firestore#42]
Hi, awesome lib!

I am using it with RN with some geohashing like this:

```javascript
  const { data } = useCollection<IBusiness>('businesses', {
    where: [
      ['geohash', '>=', range.lower],
      ['geohash', '<=', range.upper],
    ],
  });
```

But when I add 1 more `where` item, I get `too many rerenders` error and sometimes `undefined`.

```javascript
  const { data } = useCollection<IBusiness>('businesses', {
    where: [
      ['geohash', '>=', range.lower],
      ['geohash', '<=', range.upper],
      ['type', '==', 'Delivery'],
    ],
  });
```

Am I doing it correctly or am I missing something?

**Comment by nandorojo** [comment]
What's the error? Does firestore allow this query? You probably have to make a custom index if it does, which isn't related to this library in particular.

**Comment by sorxrob** [comment]
> What's the error? Does firestore allow this query? You probably have to make a custom index if it does, which isn't related to this library in particular.

You are right, I need index for this. Weird that it doesn't throw any index errors. In RN it throws too many rerender error. In Web it's just undefined without any error.

**Comment by nandorojo** [comment]
That is odd, but glad we found the problem!
