### ISSUE TITLE
Does it work with the Firebase emulator?

### ISSUE THREAD

**Issue by ChristoRibeiro** [nandorojo/swr-firestore#43]
Hi @nandorojo and nice work on this library! Does it work with the Firebase emulator? If not, it could be nice to be.

**Comment by nandorojo** [comment]
This library only concerns itself with fetching on the client side with firestore under the hood. So if that can work with the emulator, I don't see why not.

You probably just need to do something like:

```js
const fuego = new Fuego(...)

fuego.db.settings({ host: "localhost:8000", ssl: false })
```
