### ISSUE TITLE
Why use @firebase/firestore-types?

### ISSUE THREAD

**Issue by goleary** [nandorojo/swr-firestore#45]
Seems like it is an opportunity for the `@firebase/firestore-types` & `firebase` libraries to get out of sync with each other.

Did you ever think about importing the types from the `firebase` library instead?
![image](https://user-images.githubusercontent.com/16123225/92664832-e7cc0300-f2b9-11ea-9cd9-ab06d29fca3c.png)

**Comment by nandorojo** [comment]
Sure, but it would probably be `import type { firestore } from 'firebase'`

**Comment by goleary** [comment]
not sure I follow

**Comment by nandorojo** [comment]
I'd accept a PR on this if you'd like.
