### ISSUE TITLE
Have any utils for merging sub collections and other root level collections?

### ISSUE THREAD

**Issue by devhyunjae** [nandorojo/swr-firestore#48]
https://firebase.google.com/docs/firestore/manage-data/structure-data#root-level_collections

<img width="884" alt="Screen Shot 2020-10-12 at 11 02 08 AM" src="https://user-images.githubusercontent.com/12890257/95697653-67af0980-0c7a-11eb-904d-92a6d63e3f64.png">

Is there a util or helper to query `rooms` collection with `from` field as `users document` joined?

`const rooms = useCollection('rooms').(with something)`

```
rooms.data = [{
  id: 'software',
  messages: [{
    id: 'message1',
    from: {
      id: 'alovelace',
      first: 'Ada',
      last: 'Lovelace',
      born: 1815
    }
  }]
}]
```

Or should I fetch each data separately and loop & merge manually?

**Comment by devhyunjae** [comment]
smells like this is a firebase limitation. will close

**Comment by nandorojo** [comment]
I don’t exactly understand what you want to do. Would collection group queries solve what you need? If so, try the undocumented `useExperimentalCollectionGroup`.

**Comment by jerber** [comment]
Firestore does not have a "from" option.

**Comment by devhyunjae** [comment]
@nandorojo Thanks for the response. I already tried but it shows the data without the sub-collection inside.
I think firestore doesn't provide a way to get collections and sub-collections all together in just 1 query.

**Comment by devhyunjae** [comment]
@jerber from is not a option in there. it is a string type field that has the user document's id

**Comment by jerber** [comment]
@devhyunjae got it. There is a way to query multiple collections via collection group queries. A collection group query would query all collections that share the same collection name. So if you made your outer collection the same name as your inner one, that should work.

**Comment by jerber** [comment]
You would not be able to perform different queries on the collections though... would have to be the same query spanning all collections with the same name.

**Comment by nandorojo** [comment]
@devhyunjae you're correct, it does not.

You could loop though each document in your collection, render a component for each one, and call `useCollection` within each one of those components to get the subcollections.

An example would be, you fetch your inbox, which is a list of room documents. Each room has a messages subcollection. When you open a room, you fetch its `messages` subcollection using its ID.

**Comment by Lucas-Geitner** [comment]
Hello, i think @devhyunjae would like a populate function like it exist on redux-firebase

https://github.com/prescottprue/redux-firestore#population
http://react-redux-firebase.com/docs/recipes/populate.html (Version with RTDB)
