### ISSUE TITLE
Reserved keyword "id" and how to work with it?

### ISSUE THREAD

**Issue by gugahoi** [nandorojo/swr-firestore#49]
For my data models I often have "id" as a field in my documents. I assume this is a common thing (I have no stats to back this up tho). Is there or would you consider a way to transform "id" from the document into another name with some configurable option as to avoid this conflict? Alternatively, is it possible to configure the library to itself look into a field other than `id`?

**Comment by nandorojo** [comment]
Hm interesting, haven’t thought about that. IDs are a very core concept of firestore documents. Where do you use an ID inside of them? I assume an ID inside of the document should be named more specifically if it isn’t the ID of the document itself.

**Comment by gugahoi** [comment]
It is the id of the document itself most of the time. I guess my point was that it would be easier to allow the library to be configurable than to update the way models have been structured. `id` and `exists` are pretty common words that I imagine are used in models (at the very least I have used them). 

From memory, the reason I started using `id` as a field was related to how I needed to add data. I was querying information from a external system and wanted to store it, but I had no guarantee that this ID would be unique, so instead of forcing the ID of the document to match the ID of the external system I simply kept it as a field and allowed firebase to generate the document ID for me.

**Comment by nandorojo** [comment]
Got it, I would probably recommend using a more specific field than `id` and `exists` to stay consistent with the Firestore approach. These are fields that are innate to the document snapshot.

**Comment by gugahoi** [comment]
So I guess my question still stands. Say I have several models that have `id` fields and I'd like to use this library. Is there any way I can give it some converter function so that it differentiates between the `id` field that is part of the `data()` versus the `id` field that is part of the `snapshot`?  Even tho `id` and `exists` are part of a `snapshot`, when  working with the SDK, the *data* of the snapshot and the *properties* of the snapshot are separated.

Conversely, things seem to work regardless but I get warnings in the console, what are the potential impacts of these warnings?

**Comment by nandorojo** [comment]
It seems like #46 could solve this.

**Comment by nandorojo** [comment]
As it stands, this library overwrites your ID field with the document ID when it displays your data. The warning is only meant to let you know of that when you’re in development.

**Comment by dhazeley** [comment]
@nandorojo Just to add some context to this issue, a major reason most people add the document id to the document data is for collection group queries. If you need to query a collection group and find a single document, it's not possible to query for the document's id. The only workaround is to store the id in the document so you can then do a collection group query with a where in clause. I know there's a plethora of people who do this exact thing.

If we can implement the proposed solution of transforming either of the conflicting id fields, that would be ideal as most people won't have the flexibility to do a mass migration on their firestore documents just to be compliant with this library's standards.
Alternatively, an option to suppress this warning in development would suffice for those who use the id field for this purpose.
