### ISSUE TITLE
Unsubscribing from a document listener

### ISSUE THREAD

**Issue by gugahoi** [nandorojo/swr-firestore#50]
I am struggling to find documentation on how to unsubscribe a listener. It seems the `unsubscribe` functions is not returned when using `useDocument` for example. Any way to achieve this today or is this an improvement that needs to be made? If it is, I am happy to take a crack at it.

**Comment by nandorojo** [comment]
Currently this is handled for you on unmount.

To do this on you’re own, `useCollection` and `useDocument` would need to return the `unsubscribeRef.current` field as `unsubscribe`. I think that behavior makes sense, I’d accept a PR if you’d like to contribute it!

**Comment by nandorojo** [comment]
Published in `0.14.1`. Docs: https://github.com/nandorojo/swr-firestore/blob/master/README.md#usecollectionpath-query-options

**Comment by gugahoi** [comment]
That was quick, thanks!
