### ISSUE TITLE
Chaining Requests

### ISSUE THREAD

**Issue by lifeinafolder** [nandorojo/swr-firestore#52]
Hi,

I am trying to do 2 requests in my component but it seems like that the 2nd request is never succeeding.

```  
const { data, error } = useCollection("paths", {
    where: ["slug", "==", slug],
  });

  const path = data && data[0];
  const { creator, isLoadingCreator, isCreatorError } = useDocument(path?.author ? `authors/${path.author}` : null);

return (
          <Box>
            <PathMetaData path={path} creator={creator}/>
          </Box>
)
```

If I mount my 2nd request in the child component `PathMetaData`, it works. However, I need to do it at this level as it is needed by another child component.

What am I missing? I have tried https://swr.vercel.app/docs/conditional-fetching as well,

```
const { creator, isLoadingCreator, isCreatorError } = useDocument(() => `authors/${path.author}`);
```

but no luck.

**Comment by nandorojo** [comment]
You should be getting `data`, not `creator`.

**Comment by lifeinafolder** [comment]
Thank you for this.
