### ISSUE TITLE
Issue with refetching data when auth changes

### ISSUE THREAD

**Issue by AlexanderArvidsson** [nandorojo/swr-firestore#54]
I'm using this with [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) and having an issue once the user logs in.

The rules in the firestore is set to only allow authenticated users to access the resource. Non users cannot see the data initially, and one would expect that once they login and get redirected back to the page, it would fetch the new data. However, that does not seem to be the case, since I have to do a proper page reload in order for the data to show. It's like it is not performing another network fetch when I re-render the component,

Also, even if I go to another page and then back (which will re-render the page and run the hook), the data does not show.

Am I doing something wrong? I would expect that the hook would re-fetch the data every time the hook runs (cache and network strategy)? If I use react-redux-firebase method of fetching data, it is synced perfectly fine.

Here's the snippet of code I am using
```typescript
  const { data: shares, add, revalidate } = useCollection<{ name: string }>(
    "share",
    {
      listen: true,
    }
  );
```
And to login:
```typescript
  const loginWithGoogle = () => {
    return firebase.login({ provider: "google", type: "popup" });
  };
```

The same issue applies when logging out as well, however in that case I want to clear the entire cache on logout. Using `cache.clear()` from `swr` does not seem to work either.

**Comment by nandorojo** [comment]
Try passing `null` as the collection if there is no `uid` set yet. If there is a `uid`, then use `shares` as the collection. This ensures it will only fetch when it can.

**Comment by nandorojo** [comment]
I'm surprised clearing the cache doesn't work. I use that method myself and it works fine. Can you reproduce this in a code sandbox?

**Comment by nandorojo** [comment]
You can also try passing `revalidateOnMount: true` to see if that changes anything.

**Comment by AlexanderArvidsson** [comment]
I'm not sure I understood what you meant with passing null as the collection. I want to fetch all documents in the collection `share`.

How do I pass `revalidateOnMount: true` to it? The options type do not have it so I cannot pass it along to swr.

I haven't tested the cache clearing thorougly, but running it in `onAuthStateChanged` does not clear the data (when I get redirected back to the original page, the data is still there even though I ran `cache.clear()`.
Reproducing it in a codesandbox would take time since auth is involved, time that I unfortunately do not have right now.
If you have an existing codesandbox with auth then I could reproduce it with that as a base.

**Comment by nandorojo** [comment]
If a user isn't signed in, pass `null` as the first argument of `useCollection`.

https://github.com/nandorojo/swr-firestore#use-dynamic-fields-in-a-request

**Comment by AlexanderArvidsson** [comment]
That did the trick for logging in! However, why does `swr` not re-fetch on render like the ordinary `userSWR` does? I am not providing `revalidateOnMount` in my regular `useSWR` hook, so why would it be different?

The point of `swr` is that it uses a cache and network approach, does this package have a different goal?

I made a button that calls `cache.clear()` and it does absolutely nothing on click, even if I click it, go to another page and go back. Data still there.

**Comment by nandorojo** [comment]
That is the goal, so it may be a bug. You could make a code sandbox with a collection that doesn't have permissions if you want to reproduce it, since I haven't heard of this happening before. 

Could you see if removing `listen` solves it?

**Comment by AlexanderArvidsson** [comment]
I did attempt removing listen, no difference unfortunately.
Guess I will have to make a codesandbox. Again, do you have one I can use as a base to speed things up? :)

I find it odd that the cache is not getting cleared though. Is there a way to inspect the cache of swr? I have only recently started using swr.

**Comment by nandorojo** [comment]
https://github.com/Lucas-Geitner/next-js-swr-firestore-exemple

You can import that on code sandbox

**Comment by AlexanderArvidsson** [comment]
So, I was creating the codesandbox to reproduce the error and it worked perfectly fine there.
I decided to update ALL my packages to the most recent version (project is in an initial stage anyway) and it seems to have done the trick. I also do not have to clear the cache in `onAuthStateChanged` anymore either.

These are the changes
```
 @fullhuman/postcss-purgecss          ^2.1.0  →     ^3.0.0
 @types/recharts                      ^1.8.9  →    ^1.8.16
 color                                ^3.1.2  →     ^3.1.3
 firebase                            ^7.21.1  →    ^7.24.0
 firebase-admin                       ^9.2.0  →     ^9.3.0
 framer-motion                        ^2.7.6  →     ^2.9.4
 next                                 ^9.5.3  →     ^9.5.5
 nookies                              ^2.4.0  →     ^2.4.1
 react                              ^16.13.1  →    ^17.0.1
 react-dom                          ^16.13.1  →    ^17.0.1
 twin.macro                          ^1.10.0  →    ^1.11.1
 @types/lodash                     ^4.14.149  →  ^4.14.162
 @types/node                        ^14.11.2  →   ^14.14.3
 @types/react                       ^16.9.49  →   ^16.9.53
 @typescript-eslint/eslint-plugin    ^2.26.0  →     ^4.5.0
 @typescript-eslint/parser           ^2.26.0  →     ^4.5.0
 babel-plugin-root-import             ^6.5.0  →     ^6.6.0
 eslint                               ^6.8.0  →    ^7.12.0
 eslint-plugin-prettier               ^3.1.2  →     ^3.1.4
 eslint-plugin-react                 ^7.19.0  →    ^7.21.5
 postcss-import                      ^12.0.1  →    ^13.0.0
 tailwindcss                         ^1.8.10  →     ^1.9.6
```

Only thing I can think of is that the firebase package was updated and react was updated to 17.
Other than that, it seems to be working fine now!

**Comment by nandorojo** [comment]
Sounds good.

And that option is already included, please check out the readme API section for `useCollection`. Any SWR options can be passed as a third argument dictionary.

**Comment by AlexanderArvidsson** [comment]
Ah! I was looking in the code and had thought it was the second argument that gets passed in.
Anyway, great job on this, very well made!

**Comment by Lucas-Geitner** [comment]
Hello @AlexanderArvidsson, 

Thanks for testing the sandbox, i just updated the package so it's working now,

**Comment by nandorojo** [comment]
I'm glad it's useful. Feel free to star if you haven't, or share on Twitter to help others find it. https://twitter.com/fernandotherojo
