### ISSUE TITLE
Add support for Firebase 8.0.0

### ISSUE THREAD

**Issue by ouuyeah** [nandorojo/swr-firestore#58]
If firebase gets updated to 8.0.0 app will stop working because: TypeError: Cannot read property 'length' of undefined, and comes maybe from this file:
https://github.com/nandorojo/swr-firestore/blob/master/src/classes/Fuego.ts

Is also maybe related to this one:
https://stackoverflow.com/questions/64545862/upgrade-to-firebase-js-8-0-0-attempted-import-error-app-is-not-exported-from

Thanks for a great package @nandorojo ;)

**Comment by nandorojo** [comment]
Interesting, looks like v8 requires a default import. I'm not using v8 myself, but this might need its own branch / tag to support that. I can do that when I upgrade.

**Comment by nandorojo** [comment]
Solution [here](https://github.com/nandorojo/swr-firestore/issues/59#issuecomment-719950071) btw.
