### ISSUE TITLE
Add support for Firebase 8.0.0

### ISSUE THREAD

**Issue by hipdev** [nandorojo/swr-firestore#59]
If firebase gets updated to 8.0.0 app will stop working because TypeError: Cannot read property 'length' of undefined, and comes maybe from this file:
https://github.com/nandorojo/swr-firestore/blob/master/src/classes/Fuego.ts

Is also may be related to this one:
https://stackoverflow.com/questions/64545862/upgrade-to-firebase-js-8-0-0-attempted-import-error-app-is-not-exported-from

Thanks for a great package @nandorojo ;)

**Comment by nandorojo** [comment]
#58

**Comment by nandorojo** [comment]
For now, you can copy the contents of that file, make your own `Fuego` with the default import, and pass that to the `FuegoProvider` like normal.

**Comment by nandorojo** [comment]
Just do this in your app:

```ts
// fuego.ts
import firebase from 'firebase/app'

type Config = Parameters<typeof firebase.initializeApp>[0]

export class Fuego {
  public db: ReturnType<firebase.app.App['firestore']>
  public auth: typeof firebase.auth
  public functions: typeof firebase.functions
  public storage: typeof firebase.storage
  constructor(config: Config) {
    this.db = !firebase.apps.length
      ? firebase.initializeApp(config).firestore()
      : firebase.app().firestore()
    this.auth = firebase.auth
    this.functions = firebase.functions
    this.storage = firebase.storage
  }
}
```

```diff
- import { Fuego } from './fuego'
+ import { Fuego } from '@nandorojo/swr-firestore'
```

**Comment by armouti** [comment]
hey @nandorojo just checking if there's any plans to add native support for firebase 8

**Comment by nandorojo** [comment]
Hey, I haven't upgraded myself quite yet, but I can upgrade this when I do. The solution above should work, though.

**Comment by armouti** [comment]
@nandorojo thank you for that. Unfortunately this solution seems to be breaking the types ?

![Screenshot 2021-01-24 at 20 24 05](https://user-images.githubusercontent.com/37476568/105642542-4b7a5580-5e82-11eb-8a8b-4a9d0113bdfd.png)

**Comment by nandorojo** [comment]
You should still import lowercase `fuego` from this library directly in the rest of your app.

**Comment by armouti** [comment]
yes that is what I'm doing
`import { fuego } from '@nandorojo/swr-firestore';`

**Comment by nandorojo** [comment]
Hm, I see. What if you instead import your own `fuego` then?

**Comment by armouti** [comment]
yes you're right, that fuego instance seems to have the correct typings, thanks

**Comment by grissproject** [comment]
JS version:

```
import firebase from 'firebase/app';

export default class Fuego {
  constructor(config) {
    this.db = !firebase.apps.length
      ? firebase.initializeApp(config).firestore()
      : firebase.app().firestore();
    this.auth = firebase.auth;
    this.functions = firebase.functions;
    this.storage = firebase.storage;
  }
}
```
Then
`import Fuego from 'config/Fuego';`

**Comment by andrewtsun25** [comment]
just wondering why can't you reference `firebase.apps.length` as such? this is a feature in TypeScript called [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html).

```
firebase?.apps.length
```

this would still compile in TypeScript and would not break for v7 nor v8 and would solve everyone's problems listed above with minimal effort (i.e. would not need to upgrade Firebase)

**Comment by nandorojo** [comment]
It’s not because it’s undefined. It’s because firebase 8 imports default, while v7 imports imports `* as firebase`

**Comment by andrewtsun25** [comment]
ahhhhh i see, so the `firebase` object is fundamentally different.
