### ISSUE TITLE
__DEV__ not defined

### ISSUE THREAD

**Issue by nk1tz** [nandorojo/swr-firestore#6]
<img width="526" alt="Screen Shot 2020-05-18 at 6 16 38 PM" src="https://user-images.githubusercontent.com/12980165/82264907-cb374400-9933-11ea-9273-381a2fda3849.png">

**Comment by nandorojo** [comment]
Interesting, where are you running this? Next.js? I'll add a check for `__DEV__` (this was originally made to target `React Native`, so it didn't occur to me)

**Comment by nk1tz** [comment]
Yes Nextjs

**Comment by nk1tz** [comment]
Any presets i can add that to next.config that might populate this for me?

**Comment by nandorojo** [comment]
Good question. I've used the `@expo/next-adapter` and `expo-next-react-navigation` to use React Native + Next, so those probably made this variable for me. 

You could probably put this in your `pages/_app.tsx`:
```js
global.__DEV__ = true // or false if you want
```

That said, it probably makes more sense for me to update the library to get rid of `__DEV__` altogether.

**Comment by nandorojo** [comment]
This should fix it:

https://github.com/nandorojo/swr-firestore/commit/0c204d188a4f94faaa15672bda0df5581d6c9196#diff-b09d901112edb36d8fb8e29fdd72c5fb

Could you try installing the latest version (`0.7.2`) and see if the error goes away?

**Comment by nk1tz** [comment]
You `global.__DEV__ worked.
I'll update to your latest right now.

🙏 ty for responsiveness :):)

**Comment by nandorojo** [comment]
Awesome! Of course, happy to help.

**Comment by nk1tz** [comment]
Ok looks like we're missing an export somewhere perhaps:
```
error - ./node_modules/@nandorojo/swr-firestore/lib/module/hooks/use-swr-document.js
Module not found: Can't resolve 'src/helpers/is-dev' in '/Users/nkitzke/Workspace/veriphi/node_modules/@nandorojo/swr-firestore/lib/module/hooks'
Error: Cannot find module 'src/helpers/is-dev'
```

**Comment by nandorojo** [comment]
Ah sorry about that, should be fixed in `0.7.3` now.

**Comment by nk1tz** [comment]
Bro! Thank you! Looks good on my end.

You're the best

**Comment by nk1tz** [comment]
I shilled you on Twitter :D
https://twitter.com/nk1tz/status/1262511788123357186

**Comment by nandorojo** [comment]
Sweet! Thanks for the heads up

**Comment by nandorojo** [comment]
Closing this out, thanks again!
