### ISSUE TITLE
Compatibility with reactfire

### ISSUE THREAD

**Issue by brunoalano** [nandorojo/swr-firestore#60]
Hello,

It's possible to use [swr-firestore](https://github.com/nandorojo/swr-firestore) together with [reactfire](https://github.com/FirebaseExtended/reactfire)? Or the Firebase initialization will be duplicated?

I already have read the [thread on Reddit](https://www.reddit.com/r/Firebase/comments/he3qtg/firestore_hooks_library_for_react_useswr/fvqu4lj/) comparing `swr-firestore` x `reactfire`, and I want to take advantage of both worlds (SWR + Lazy Loading/Suspense)

**Comment by nandorojo** [comment]
I'm not familiar with how React Fire works, but as far as I know, initialization shouldn't be duplicated. This lib first checks if you already have Firebase apps created before initializing firebase. 

I can't speak to the effects on Suspense, but you'll get all the benefits of SWR with this lib.

**Comment by nandorojo** [comment]
Once react says concurrent mode is stable for network requests, this lib will probably move towards it. Until then, I don't intend to add it.
