### ISSUE TITLE
where clause doesn't use correct type when returning data if property is nested

### ISSUE THREAD

**Issue by mjbates7** [nandorojo/swr-firestore#61]
Hello, when using a where clause in which you specify a nested property, it makes the data variable that is returned not map to the type that you've specified. 

See below screenshot:

![image](https://user-images.githubusercontent.com/4522738/97719809-6d508000-1abf-11eb-8fe5-7716de1d1c9b.png)

I would expect to see those properties, plus the properties from the type that I pass in.

Any ideas on this? Possibly related to #53

**Comment by nandorojo** [comment]
Seems like an effective duplicate of #53. What if you `@ts-ignore` above where, does that do anything?

**Comment by nandorojo** [comment]
Fixed in `0.16.0`
