### ISSUE TITLE
react-native-firebase support

### ISSUE THREAD

**Issue by henrymoulton** [nandorojo/swr-firestore#63]
Hey there @nandorojo great stuff!

I remember coming across this a while back. I wondered if it supports React Native Firebase? I'm currently using it with the Expo Bare Workflow. I'll add a 1 liner to the docs if so :)

**Comment by nandorojo** [comment]
Hey @henrymoulton, thanks!

Could you try this? https://github.com/nandorojo/swr-firestore/issues/39#issuecomment-681046958

**Comment by henrymoulton** [comment]
Will do thanks @nandorojo, Dripsy looks pretty cool too (currently using Restyle tho)... 

Seems you're pushing the universal React Native train pretty hard which is awesome :D

**Comment by nandorojo** [comment]
Appreciate that. I don't have experience using Restyle but it looks like it gets the job done (like `styled-system` for native). Dripsy starts to stand out more when you want to use web.

I'm working on a full UI library based on Dripsy at the moment. Also, if you're interested in Reanimated 2, you can follow [this idea](https://github.com/nandorojo/redrip).

I love React Native, but when it comes to design systems and web-supported animations, it can far behind. Gotta catch it up 🚀
