### ISSUE TITLE
How to access cache and mutate

### ISSUE THREAD

**Issue by samipshah100** [nandorojo/swr-firestore#65]
I have a quick question if you can help please. 

I want to use https://www.npmjs.com/package/@jjordy/swr-devtools

How to access `cache` and `mutate`.  to use with `<SWRDevtools cache={cache} mutate={mutate} />`

The following is not working

```
import { FuegoProvider } from '@nandorojo/swr-firestore'
import { cache, mutate } from 'swr'

function app (){return(
 <>
      <SWRConfig
        value={{
          errorRetryCount: 2,
        }}
      >
        <FuegoProvider fuego={fuego}>
          <app/>
        </FuegoProvider>
      </SWRConfig>
      <SWRDevtools cache={cache} mutate={mutate} />
    </>
)}
```

Thanks a lot /\

**Comment by nandorojo** [comment]
This library uses SWR under the hood, nothing special to it. I'm not familiar with that package, but I don't see why it wouldn't work.

Also, this example is not valid JSX. `app` must be capitalized.****

**Comment by nandorojo** [comment]
I took a look at that library. It might be due to the version of `swr` this one uses. Try adding this to your `package.json`:

```json
{
  resolutions: {
    swr: "latest"
  }
}
```

And then run `yarn install`. This will not work with npm.

**Comment by samipshah100** [comment]
Thanks @nandorojo for your suggestion. I appreciate it. I will try this.

**Comment by samipshah100** [comment]
Thanks @nandorojo 

`latest` didnt work but 
```
"resolutions": {
    "swr": "^0.3.9"
  }
``` 

It works. I can see the devtools data now. Thanks :D

I noticed this lib is using swr 0.2
Is it ok to use 0.3.9 in production or do you suggest against it?

**Comment by nandorojo** [comment]
Yeah you should be good to use that version.

**Comment by samipshah100** [comment]
Coolio! Thanks agian
