### ISSUE TITLE
Date error while adding firebase.firestore.FieldValue.serverTimestamp() 

### ISSUE THREAD

**Issue by samipshah100** [nandorojo/swr-firestore#68]
Let's say I am adding a document to a collecting using firestore timestamp, i.e.
`firebase.firestore.FieldValue.serverTimestamp(),`

```
const { data, add } = useCollection('albums', {
  where: ['artist', '==', 'Drake'],
})

const onPress = () => {
  // calling this will automatically update your global cache & Firestore
  add({
    title: 'Dark Lane Demo Tapes',
    artist: 'Drake',
    year: '2020',
createdAt: firebase.firestore.FieldValue.serverTimestamp(),
  })
}
```

Now this doc is added to the swr cache using mutate. This returns a rendering error since the date in the swr cache is still a non-serializable firestore timestamp. 

I will try to solve it by checking the date before rendering. 
But I wanted to ask if any suggestion to elegantly solve it. 

Thanks.

**Comment by nandorojo** [comment]
Can you try `parseDates` from the [docs](https://github.com/nandorojo/swr-firestore)?

```js
const { data, add } = useCollection('albums', {
  where: ['artist', '==', 'Drake'],
  parseDates: ['createdAt']
})
```

**Comment by nandorojo** [comment]
On second thought, doesn't look like that'll work. I suggest using the native `fuego.db.collection().add()` function and then revalidate this query by calling `mutate()` returned by `useCollection`.

**Comment by samipshah100** [comment]
Yes I tried parseDate but seems like it's only for reads (where it works just nice thanks)

Seems like can be solved by modifying this piece of code at line 518 of `/use-swr-collection.ts`
viz.
```
     mutate(prevState => {
          const state = prevState ?? empty.array
          return [...state, ...docsToAdd]
        }, false)
      }
```

by adding the toDate function here ^

but i am lacking confidence in my solution to submit a pull request haha just brining it to your notice. 

....


So you mean I just call `mutate()` without any key or args and it will revalidate the data from firestore? 

Thanks man thats cool

**Comment by nandorojo** [comment]
> So you mean I just call mutate() without any key or args and it will revalidate the data from firestore?

That's correct, as long as it's the function returned by the `useCollection` hook.

**Comment by nandorojo** [comment]
Alternatively, if you add `listen: true` then this should also work.
