### ISSUE TITLE
How to use pagination?

### ISSUE THREAD

**Issue by Qrymy** [nandorojo/swr-firestore#7]
Hi! It's a great library to use Firestore with React.

Do you have a feature to use `pagination` for infinite scroll?

**Comment by nandorojo** [comment]
Hey, thanks!

I don’t currently have this baked in, but I’ll add it to the list.

For now, you can use a `limit` state variable, and pass it to your collection query.

```js
const [limit, setLimit] = useState(10)
const { data } = useCollection(‘users’, { limit })

const paginate = () => setLimit(currentLimit => currentLimit + 10)
```

**Comment by Qrymy** [comment]
Thanks for your response!
But I think your example is not good because

## Normally
1. get 10 documents.
2. get 10 documents. (from 11th to 20th)
more...

## Your example
1. get 10 documents.
2. get 20 documents.
3. get 30 documents.
more...

How do you think?

**Comment by nandorojo** [comment]
Yeah, it’s an imperfect solution. The alternative is to do pagination requests directly to Firestore, and use the `mutate` function to update the local cache. If you want, I can show you an example. But I would have to think a little about it, since Firestore has many ways to paginate and it tends to be pretty custom based on use case.

**Comment by nandorojo** [comment]
This worked for me. Video [here](https://imgur.com/83iagVD).

```typescript
import React from "react";
import { fuego, useCollection } from "@nandorojo/swr-firestore";

const collection = "dump";
const limit = 1;
const orderBy = "text";

export default function Paginate() {
  const { data, mutate } = useCollection<{ text: string }>(
    collection,
    {
      limit,
      orderBy,
    },
    {
      // this lets us update the local cache + paginate without interruptions
      revalidateOnFocus: false,
      refreshWhenHidden: false,
      refreshWhenOffline: false,
      refreshInterval: 0,
    }
  );

  const paginate = async () => {
    if (!data?.length) return;

    const ref = fuego.db.collection(collection);

    // get the last document in our current query
    // ideally we could pass just a doc ID, but firestore requires the doc snapshot
    const startAfterDocument = await ref.doc(data[data.length - 1].id).get();

    // get more documents, after the most recent one we have
    const moreDocs = await ref
      .orderBy(orderBy)
      .startAfter(startAfterDocument)
      .limit(limit)
      .get()
      .then((d) => {
        const docs = [];
        d.docs.forEach((doc) => docs.push({ ...doc.data(), id: doc.id }));
        return docs;
      });

    // mutate our local cache, adding the docs we just added
    // set revalidate to false to prevent SWR from revalidating on its own
    mutate((state) => [...state, ...moreDocs], false);
  };

  return data ? (
    <div>
      {data.map(({ id, text }) => (
        <div key={id}>{text}</div>
      ))}
      <button onClick={paginate}>paginate</button>
    </div>
  ) : (
    <div>Loading...</div>
  );
}
```

**Comment by nandorojo** [comment]
Also, added to docs here: https://github.com/nandorojo/swr-firestore/blob/master/README.md#paginate-a-collection

**Comment by Qrymy** [comment]
Thanks a lot!

**Comment by nandorojo** [comment]
No problem! Closing for now

**Comment by ravenwits** [comment]
Hey there @nandorojo everything is working perfectly fine except startAfter function not starts from last snapshot but last - 1. 
So it goes like this when I set limit to 2:

Initial data: [A-B]
onPaginate: Instead of [C-D] it returns [B-C] 

when I check last snapshot of initial data it logs B as expected. I am lost here..
