### ISSUE TITLE
Revalidation issues with set/update

### ISSUE THREAD

**Issue by samipshah100** [nandorojo/swr-firestore#71]
Hi Fernando, 

My data is not in sync with the firestore when i use the update/set function on `useDocument`.

The same issue is with both `set` and update`. 

Calling `mutate` also doesnt help.

Code:

```
import React from 'react'
import { useCollection, useDocument } from '@nandorojo/swr-firestore'
import { Typography, ListItemSecondaryAction, Button } from '@material-ui/core'

export default function test() {
  var { data: userData, set, update, mutate } = useDocument(`users/test`)
  const plus = () => {
    const amt = userData.amt + 1

    update({ amt })
    // mutate()
  }
  const minus = () => {
    const amt = userData.amt - 1

    update({ amt })
    // mutate()
  }

  return (
    <div style={{ margin: 80 }}>
      {userData?.amt}
      <br />
      <Button variant="outlined" color="secondary" onClick={plus}>
        Plus
      </Button>
      <Button variant="outlined" color="secondary" onClick={minus}>
        Minus
      </Button>
    </div>
  )
}
```

Screenshot GIF capture of the behavior and firestore data

![screenshot](https://user-images.githubusercontent.com/51622592/100912607-b64c8780-34f6-11eb-94ef-751c1f03554c.gif)

Any advise? 

Am i doing anything wrong?

**Comment by nandorojo** [comment]
You should probably use firestore's built-in increment function, and set `listen: true`. Mutating a current database value based on a current database value shouldn't be done by editing the cache, since you're almost guaranteed to get data inconsistencies.

I would do this

```js
const id = 'users/test'

useDocument(id, { listen: true })

const increment = () => {
  fuego.db.doc(id).update({ amt: FieldValue.increment(1) })
}
```
