### ISSUE TITLE
Is there any way to listen to metadata changes?

### ISSUE THREAD

**Issue by wporoslo** [nandorojo/swr-firestore#72]
I'm struggling to figure out a way to track the number of active subscriptions to a document. 

In an [issue](https://github.com/firebase/firebase-android-sdk/issues/947#issuecomment-547537941) in official repo for `firebase-android-sdk` it is suggested to listen to network changes by passing `MetadataChanges.INCLUDE` into snapshot listener and in [official documentation](https://firebase.google.com/docs/firestore/query-data/listen#events-metadata-changes) this takes the form of

```
db.collection("cities").doc("SF")
    .onSnapshot({
        // Listen for document metadata changes
        includeMetadataChanges: true
    }, function(doc) {
        // ...
    });

```

Is there currently a way of including that data in the listener?

**Comment by nandorojo** [comment]
This library uses the web SDK. Does it work there?

**Comment by wporoslo** [comment]
Looks like it does: https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotListenOptions#includemetadatachanges

**Comment by nandorojo** [comment]
Yeah, I'm using meta data changes, but I don't see anything about it mentioning number of listeners.

**Comment by nandorojo** [comment]
As you'll see from the docs, `data` returns `hasPendingWrites` and `exists`.

https://github.com/nandorojo/swr-firestore#usedocument

**Comment by wporoslo** [comment]
Yeah, now I realize that what I want to achieve should be done rather through cloud functions than on the client side.

Thank you for patience and quick answers, tough.
