### ISSUE TITLE
Nextjs Firestore Server Side Data Fetching Issue

### ISSUE THREAD

**Issue by msanmaz** [nandorojo/swr-firestore#73]
`import firebase from 'firebase/app';
import 'firebase/firestore'

const firebaseConfig = {
    apiKey: 
    authDomain: 
    databaseURL: 
    projectId: 
    storageBucket: "
    messagingSenderId: 
    appId: 
    measurementId: "
}

export function firebaseDB() {
  // Initialize Firebase
  if (!firebase.apps.length) {
    firebase.initializeApp(firebaseConfig);
    // firebase.analytics();
  }
  return firebase;
}
`

I've the following fire base config, and I'm using the following syntax for getinitialprops
`static async getInitialProps(){
    let firebase = await firebaseDb()
    let db = firebase.firestore()
    let result = await new Promise((resolve,reject) =>{
        db.collection('cards')
        .get()
        .then(snapshot =>{
            let data = []
            snapshot.forEach(doc=>{
                data.push(Object.assign({
                    id:doc.id
                },data.doc()))
                
            })
            resolve(data)
        }).catch(error =>{
            reject([])
        })
    })return {cards:result}
}
`
but however I've just getting back undefined when I log, I think my config file has something wrong cause I cant await firebaseDB() as well,

**Comment by nandorojo** [comment]
This is unrelated to this library, please post an issue on firebase's repo.
