### ISSUE TITLE
Create pagination with a listener

### ISSUE THREAD

**Issue by hipdev** [nandorojo/swr-firestore#82]
Hi folks, I'm trying to create a simple chat, right now I have a query with listen: true and is working fine, my ui isupdating everytime a new message is coming and I have a limit of 10 messages, my issue is with the pagination, every time I paginate and receive a new message the query data gets reloaded and is always showing the last 10 messages not taking the old ones in the cache or those that had already paged previously.

Someone has a chat example working with pagination?
Thanks a lot!

**Comment by nandorojo** [comment]
Good question, I haven't actually encountered this use case myself. You might need to create your own layer on top of the SWR cache or something.

**Comment by jackkrebsbach** [comment]
I am also trying to create a simple chat app and I believe I am running into a similar issue. I am not paginating yet but my listener seems to confused.  @hipdev  did you ever figure out the problem?

I am using react-native-gifted-chat for messaging.  My messages seem to update perfectly in cache and firestore on the first mount. 

Here is how I store the message data which comes from a thread document which I create in firestore. I pass in ```messages``` and the function ```handleSend``` to my ```<GiftedChat />``` component which handles rendering the messages and uses  ```handleSend``` to  send messages. 

```javascript
const {thread} = route.params;
const user = {id: firebase.auth().currentUser.uid};
  const {data: userData} = useDocument(`users/${user.id}`, {listen: true});
  const {data: messages, add: messageAdd} = useCollection(
    `threads/${thread}/messages`,
    {
      listen: true,
      orderBy: ['createdAt', 'desc'],
    },
  );
  const {set: threadUpdate} = useDocument(`threads/${thread}`, {
    listen: true,
  });

  function handleSend(message) {
    const text = message[0].text;
    //message to add
    const data = {
      text: text,
      createdAt: new Date().getTime(),
      user: {
        _id: user.id,
        email: userData.email,
        name: userData.fullname,
      },
    };
    // Add message to global cache and firestore
    messageAdd(data);

    // Updating last message in global cache and firestore
    threadUpdate(
      {
        latestMessage: {
          text,
          createdAt: new Date().getTime(),
        },
      },
      {merge: true},
    );
  }
```

This seems to work great. My messages are fast and I can see them updating in firestore in realtime.  The problem I encounter is that when I unmount the messaging screen to go back to my message list my listener seems to get confused. When I remount and go into the message again my listener doesn't  catch any messages sent. 

They are still updated in firestore but that seems to be it, they do not appear in my cache. Only when I reload the app in simulator do they appear.

Are there any SWR options that I should be passing into ```useCollection``` ? 

Here is a video of starting a new message:

https://user-images.githubusercontent.com/62705622/107608695-a203d400-6c77-11eb-99ae-1e2c8b147562.mov

Here I am chatting from both users and its working great: 

https://user-images.githubusercontent.com/62705622/107608742-c2339300-6c77-11eb-9395-89a5f1966c50.mov

Here is where the listener seems to stop working. I go back to my message list and then back into the message and my messages stop appearing in the senders chat. The receiver still renders the new messages  and they are updated in firestore.  Only when I reload the app do  they appear. 

https://user-images.githubusercontent.com/62705622/107608788-e98a6000-6c77-11eb-83db-522fa15b8981.mov

Has anyone  encountered something similar? The problem could also be with ```<GfitedChat />``` but I am not sure. It seems to be with my listener. 

Any thoughts would be greatly appreciated!

**Comment by nandorojo** [comment]
@jackkrebsbach first off, cool to see someone else here from Ann Arbor (I saw that in your last video.)

I appreciate the very clear videos, I think I understand. It seems like your documents are indeed being added to Firestore, but you're saying that they aren't updating on the app.

Do you think you could recreate this situation on a simple expo snack or codesandbox? That would make it easier to debug.

One thing you could try: pass the `onSuccess` callback to the collection hook that gets your messages, and see what it's returning.

**Comment by nandorojo** [comment]
PS: if you install the Prettier code extension then right click on your penguin, it will help you prettify your example from GitHub comments. This is useful to try to read through it.

**Comment by jackkrebsbach** [comment]
@nandorojo  Go Blue! I have not used expo or code sandbox before but I will try to get something up and running soon. 

For the ```onSuccess``` callback should I put any variables to print in  ```console.log``` using   ```onSuccess: console.log```?

Thanks for the prettier tip!

**Comment by jackkrebsbach** [comment]
I was not able to find the root cause of this issue, but for some reason my listener stops listening on the remount. This workaround fixes this problem by setting```{listen: true}``` on mount. 

```javascript
 const [listenBool, setListenBool] = useState(false);
  const {data: messages, add: messageAdd} = useCollection(
    `threads/${thread}/messages`,
    {
      listen: listenBool,
      orderBy: ['createdAt', 'desc'],
    },
  );

  useEffect(() => {
    setListenBool(true);
  }, []);
```
