### ISSUE TITLE
Setup Instructions lead to "firebase.apps is undefined" in Nextjs framework

### ISSUE THREAD

**Issue by SashaBayan** [nandorojo/swr-firestore#86]
Hi @nandorojo -- thanks for putting together this amazing tool. I am excited to start using it, but I have bumped up against an error in the setup process.

I have run `npm install @nandorojo/swr-firestore`, and `npm i firebase` .

I am working in a Nextjs environment, and my `pages/_app.tsx` files reads as the setup instructions suggest:

```ts
import '../styles/globals.css';
import 'firebase/firestore';
import 'firebase/auth';
import { Fuego, FuegoProvider } from '@nandorojo/swr-firestore';

const firebaseConfig = {
  apiKey: '...',
  authDomain: '...',
  projectId: '...',
  storageBucket: '...',
  messagingSenderId: '...',
  appId: '...',
  measurementId: '...',
};
const fuego = new Fuego(firebaseConfig);

export default function App({ Component, pageProps }) {
  return (
    <FuegoProvider fuego={fuego}>
      <Component {...pageProps} />;
    </FuegoProvider>
  );
}
```

When I run `npm run dev` and navigate to `localhost:3000`, the app has crashed with the following error in the console:

`Error was not caught TypeError: firebase.apps is undefined`, with the stack trace:

<img width="566" alt="Screen Shot 2021-01-21 at 7 55 56 PM" src="https://user-images.githubusercontent.com/7477387/105399447-ed503700-5c23-11eb-9369-6d3e6e169d67.png">

There error seems to be happening in the `Fuego` instantiation. Are you aware of anything that may be causing this error?

**Comment by taseentanvir** [comment]
have you got any solution or it's a bug?

**Comment by nandorojo** [comment]
@SashaBayan thanks!

This is due to firebase 8's breaking change. 

The solution can be found here: https://github.com/nandorojo/swr-firestore/issues/59#issuecomment-719950071
