### ISSUE TITLE
useCollection and useDocument in same component

### ISSUE THREAD

**Issue by jackkrebsbach** [nandorojo/swr-firestore#87]
I want to be able to subscribe to a users document and also my collection of message threads where I filter them based off of data from my users.  However, I can't  do this because of declaring the same variables twice. Is there anyway to change the names of the objects returned by useDocument and useCollection? I'm not sure if there is a simple fix or I am missing something. 

```javascript 
  const {data, update, error} = useDocument('users/example_user');
  const {data, update, error} = useCollection('message_threads', {
    where: ['thread_id', 'in', ['thread_array']],
    listen: true,
    ignoreFirestoreDocumentSnapshotField: false,
  });
```
Is there a way where I can subscribe to my document and collection like this? 

```javascript 
  const {userData, userUpdate, userError} = useDocument('users/example_user');
  const {threadData, threadUpdate, threadError} = useCollection('message_threads', {
    where: ['thread_id', 'in', ['thread_array']],
    listen: true,
    ignoreFirestoreDocumentSnapshotField: false,
  });
```
Or if there is alternatives? Thanks @nandorojo  for such a great package!

**Comment by armouti** [comment]
You can rename destructured variables like so:

```
const { data: userData, update: userUpdate, error: userError } = useDocument('users/example_user');
  const { data: threadData, update: threadUpdate, error: threadError } = useCollection('message_threads', {
    where: ['thread_id', 'in', ['thread_array']],
    listen: true,
    ignoreFirestoreDocumentSnapshotField: false,
  });
```

**Comment by jackkrebsbach** [comment]
> You can rename destructured variables like so:
> 
> ```js
> const { data: userData, update: userUpdate, error: userError } = useDocument('users/example_user');
> const { data: threadData, update: threadUpdate, error: threadError } = useCollection('message_threads', {
>   where: ['thread_id', 'in', ['thread_array']],
>   listen: true,
>   ignoreFirestoreDocumentSnapshotField: false,
> });
> ```

**Comment by jackkrebsbach** [comment]
Thank you! I figured I was missing some basic like that.

**Comment by nandorojo** [comment]
Also I believe `update` is only returned by `useDocument`.

**Comment by jackkrebsbach** [comment]
That's right, looks the equivalent would be `add' for `useCollection`.
