### ISSUE TITLE
Is there a global onError handler?

### ISSUE THREAD

**Issue by narkeeso** [nandorojo/swr-firestore#88]
SWR has a component called `SWRConfig` where you can specify a global error handler. Does swr-firestore implement this?

**Comment by nandorojo** [comment]
You can use any SWR features like that if you want. I believe this works unless you have `listen: true`. There's an open issue for that.

**Comment by narkeeso** [comment]
I have something like this defined in the app entrypoint. It doesn't seem like onError is working. Is there a configuration I am missing so that swr-firestore is aware of the config?

```jsx
      <SWRConfig
        value={{
          onError: (err) => {
            captureException(err);
          },
        }}
      >
        <FuegoProvider fuego={fuego}>
          ...
        </FuegoProvider>
      </SWRConfig>
```

**Comment by nandorojo** [comment]
Hmm, don't think so. I'm not sure if Firestore reliably throws good errors then. Are you producing an error that isn't getting caught?

**Comment by narkeeso** [comment]
I can catch the errors using the error thrown from `useCollection` or `useDocument` just fine but I'm trying to avoid having to write error tracking for each call.

**Comment by nandorojo** [comment]
Oh got it, that I'm not sure about then. I'm not doing anything special with SWR's errors. What happens if you do a normal firestore get in a `useSWR` function yourself?

**Comment by nandorojo** [comment]
If you pass `onError` to the hook does it work?

**Comment by narkeeso** [comment]
> If you pass `onError` to the hook does it work?

Passing `onError` to the `useDocument` and `useCollection` hook work just fine.

**Comment by nandorojo** [comment]
In that case, I'm not sure. Might be an issue with SWR. Make sure you don't call the hook's `onError` or it'll override the global one.

**Comment by narkeeso** [comment]
> Oh got it, that I'm not sure about then. I'm not doing anything special with SWR's errors. What happens if you do a normal firestore get in a `useSWR` function yourself?

I just tried using a normal useSWR hook and the global onError handler is working.

**Comment by narkeeso** [comment]
Closing for now until I have time to debug why this is happening exactly.
