### ISSUE TITLE
dependent fetches throw typeError

### ISSUE THREAD

**Issue by joed1rk** [nandorojo/swr-firestore#9]
Hey I'm really enjoying the lib. 

I've noticed a typeError being thrown out from `{error} = useDocument...` whenever I setup up dependent fetches. ie:
```javascript
const { data: data1, error: error1 } = useDocument('/xxx/doc')
const { data: data2, error: error2 } = useDocument(`/yyy/${data1.prop}`)
```
When the component loads, error2 returns undefined a few times before starting to throw:
```
TypeError: Cannot read property 'db' of undefined
    at _callee$ (use-swr-document.js?a80b:1)
    at tryCatch (runtime.js?96cf:45)
```
It finally does fetch the data, but it this doesn't look like an error you'd expect such as "firestore path does not exist" for example.

**Comment by nandorojo** [comment]
Hmm, interesting. To be clear, you have the `FuegoProvider` in the root of your app, right? And the calls still work?

What if you try this:
```js
const { data: data1, error: error1 } = useDocument('/xxx/doc')
const { data: data2, error: error2 } = useDocument(data1?.prop ? `/yyy/${data1.prop}` : null)
```

If that doesn't help, I can take a look at a repo if you can reproduce it.

**Comment by joed1rk** [comment]
Yes Fuego at root :)

Oh smart. Let me give that a go

**Comment by joed1rk** [comment]
By the way, your trick totally works. Almost feels faster... I dunno

**Comment by nandorojo** [comment]
Great. Maybe we could add something to the readme to account for dynamic keys.

And that’s interesting...it could be due to making multiple Firestore requests at once?

**Comment by joed1rk** [comment]
It's good that your `useDocument` hook handles the `null` case.
:+1:
