### ISSUE TITLE
Cannot initialise - "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by ElinOlundForsling** [nandorojo/swr-firestore#91]
Tried to create a next next.js project using swr-firestore. My _app.js

```
import '../styles/globals.css';
import 'firebase/firestore';
import 'firebase/auth';
import { Fuego, FuegoProvider } from '@nandorojo/swr-firestore';

const firebaseConfig = {
  // censored :)
};

const fuego = new Fuego(firebaseConfig);

function MyApp({ Component, pageProps }) {
  return (
    <FuegoProvider fuego={fuego}>
      <Component {...pageProps} />
    </FuegoProvider>
  );
}

export default MyApp;
```

And the error I get is:

```
next-dev.js:97 Error was not caught TypeError: Cannot read property 'length' of undefined
    at new Fuego (Fuego.js:1)
    at Module.eval (_app.js:31)
```
So at the const fuego = new Fuego(firebaseConfig); line in the code.

I have high hopes for this one, hope it gets fixed :)

**Comment by nandorojo** [comment]
Looks like you're using firebase 8.

Please try this out: https://github.com/nandorojo/swr-firestore/issues/59#issuecomment-719950071

**Comment by ElinOlundForsling** [comment]
Thank you, worked wonderfully. I did not know this was connected to Firebase 8, so I'll be closing it as it's a duplicate then. Again, thank you so much, this will hopefully make my project a lot easier.

**Comment by nandorojo** [comment]
Glad to hear it!
