### ISSUE TITLE
Usage with Typescript

### ISSUE THREAD

**Issue by binajmen** [nandorojo/swr-firestore#93]
Hi,

I have two questions regarding how to use this library with TS + one subsidiary question.

```js
// pages/places.tsx
function Index(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { data: places, error } = useCollection<Place>('vendors', {}, { initialData: props.places })

  return (
    ...
      <PlacesList
        places={places}
        buttonRender={(id) => (
          ...
        )}
      />
    ...
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext) => {
  try {
    const snapshot = await admin.firestore().collection('places').get()

    if (snapshot.empty)
      return { props: { places: [] } }

    const places = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }))

    return { props: { places } }
  } catch (error) {
    console.error(error)
    return { notFound: true }
  }
}
```

```js
// PlacesList.tsx

export type PlacesListProps = {
  places: Document<Place>[] | null | undefined
  buttonRender: (id: string) => JSX.Element | null
}

export default function PlacesList({ places = [], buttonRender }: PlacesListProps) {
  // if (!places) return null

  return (
    <Box>
      <SimpleGrid columns={[1, 2, 3, 4]} spacing={6}>
        {places.map(place => <PlaceCard key={place.id} place={place} buttonRender={buttonRender} />)}
      </SimpleGrid>
    </Box>
  )
}
```

1. It is a bit verbose to typed the data with `Document<T>[] | null | undefined`. Is there a shortcut I'm unaware of?
2. Defaulting the value to `[]` in the props of `PlacesList`(`...{ places = [], ...`) is not enough: I still have the warning in VS code `var places: Document<Place>[] | null – Object is possibly 'null'.ts(2531)`. I need to uncomment the line testing the value and returning `null` to clear the error. Is it the correct way to handle this?

The subsidiary question is: is it correct to say that when passing `initialData` to `useCollection` (in this example), it will not relaunch a query against Firestore, but will just populate the cache with the data retrieved server-side. In order to avoid double-querying the database (and increase the final bill 😉 )

Thank you so much for this wonderful library! I'm only at the beginning but it seems to work like a charm!

**Comment by binajmen** [comment]
I have another example that seems overcomplicated (unless this is the way to do it, it just feels wrong to use `?` and `!` everywhere to skip the editor warnings..):

```js
  ...
  const { data: place, update } = useDocument<Place>(`vendors/${placeId}`)

  const [opening, setOpening] = React.useState<OpeningHours>(place?.opening ?? {})
  const [types, setTypes] = React.useState<string[]>(place?.types ?? [])

  React.useEffect(() => {
    setOpening(place?.opening ?? {})
    setTypes(place?.types ?? [])
  }, [place])

  function saveChanges() {
    try {
      // validate changes..

      update({ opening, types })!
        .then(() => ...)
        .catch((error) => ...)
    } catch (error) {
      ...
    }
  }
  ...
```

Am I missing something? Anyone using this library with TS?

**Comment by nandorojo** [comment]
1) why not do `if (places)` in the effect
2) why are you setting the state from an already-stateful `places` variable

**Comment by binajmen** [comment]
> 1. why not do `if (place)` in the effect
> 2. why are you setting the state from an already-stateful `place` variable

1. That would do the trick in the effect
2. I'm not sure if I understood correctly your question, but I'm using an "intermediary" state (using `useState`) to allow multiple changes before committing to Firestore
