### ISSUE TITLE
Strip down the Document property from the data itself?

### ISSUE THREAD

**Issue by binajmen** [nandorojo/swr-firestore#94]
Is there a convenient way provided by this library that I'm not aware of to remove the additional fields (`id`, `exists`, `hasPendingWrites`, `__snapshot`) from a document?

I was thinking about:
```js
const { id, exists, hasPendingWrites, __snapshot, ...rest } = data
```

**Comment by nandorojo** [comment]
That looks right!

**Comment by binajmen** [comment]
Would it make sense to add a `data()` function similar to Firestore to automate this, or am I the only one to have this need?
