### ISSUE TITLE
Basic Paging - StartAfter error with snapshot and index

### ISSUE THREAD

**Issue by joeyscarim** [nandorojo/swr-firestore#95]
I'm trying to setup a basic "next page" button like this (adapted from the infinite paging example):

```  
const [next, setNext] = useState(null);

const { data } = useCollection(`areacodes`, {
    limit: 20,
    startAfter: next,
    orderBy: 'areacode',
    ignoreFirestoreDocumentSnapshotField: false,
});

const goToNextPage = () => {
    let startAfterDocument = data[data.length - 1].__snapshot;
    setNext(startAfterDocument);
 };
```

The initial load works fine, but when I call `goToNextPage` I'm getting this error:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'FirebaseAppImpl'
    |     property 'firebase_' -> object with constructor 'Object'
    |     property 'apps' -> object with constructor 'Array'
    --- index 0 closes the circle
```

I also tried just using an index in startAfter, since the docs say it can be a number, but that isn't working either.

Any advice on how I can do a basic next page button like this?

**Comment by nandorojo** [comment]
You can’t currently pass a snapshot as startAfter, only JSON-serializable values. This is a known issue, see https://github.com/nandorojo/swr-firestore/pull/75

**Comment by joeyscarim** [comment]
Understood, thank you!
