### ISSUE TITLE
Amount of reads

### ISSUE THREAD

**Issue by HermanNygaard** [nandorojo/swr-firestore#97]
Thanks for this awesome lib! ⭐  Was just wondering, will this consume significantly more reads on the DB? Any experience with this? Considering the free tier etc.

**Comment by p-lau** [comment]
This package uses the caching technique from the `swr` package. When configured correctly, duplicate subsequent reads will refer to the cache rather than trying to make a new document read.

**Comment by samipshah100** [comment]
@HermanNygaard no, it depends on what and how you query.

**Comment by narkeeso** [comment]
We've found that it does cache the query but unless you tell it to not revalidate it will always fetch new data when you bring it into focus or remount the view. You can also turn off all the default revalidating and then control when it revalidates.

**Comment by HermanNygaard** [comment]
@p-lau but won't it still have to fetch to firebase and check? I.e. new reads.  

@narkeeso thank you, this has also been my experience so far. I turned off some default revalidates to save some reads (tab focus etc.).
