### ISSUE TITLE
Is there any way to deal with the `array-contains-any` and `in` query specifications of a limit maximum of 10?

### ISSUE THREAD

**Issue by 345ml** [nandorojo/swr-firestore#98]
Firestore's `array-contains-any` query and `in` query can specify a maximum of 10.
If the number of targets exceeds 10, you will need to split the query. 

I often deal with this problem, for example, when retrieving multiple user data.

How does this library handle this?

# What I tried.
The problem is that the `userIdsList` is dependent on other data and changes dynamically.

## Use `useCollection` case
This method will cause this error.

```
Error: Rendered more hooks than during the previous render.
```

Sample code
```js
const userIdsList = [
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
];

const data =  userIdsList.map((userIds) => {
  return useCollection(
    userIds.length > 0 ? 'users' : null,
    {
      where: ['id', 'in', userIds],
    }
  )
})
```

## Use `getCollection` case
This method works as expected.

However, I have one concern.
Internally, is there a request to `Firestore` every time this code is executed?
Or is the cache management done internally in the library, and the actual request to Firestore is only the first time?

```js
const userIdsList = [
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
];


const [users, setUsers] = useState([]);

useEffect(() => {
  Promise.all(userIdsList.map((userIds) => {
    return userIds.length <= 0 ? null : getCollection(
      'users',
      {
        where: ['id', 'in', userIds],
      },
    )
  })).then((data) => {
    console.log(data);
    
    setUsers(
      data.reduce((acc, _users) => {
        return _users === null ? acc : acc.concat(_users);
      }, [])
    )
  });
}, [userIdsList.length]);
```

**Comment by nandorojo** [comment]
If there are any maxima, that should be handled on your end.

As for the re-fetching, this library stringifies the query first, so as long as the array is deep equal in both cases, it won't refetch.

**Comment by nandorojo** [comment]
I see the problem now. You're not allowed to use hooks in a loop. This breaks the rules of hooks. Please look up the rules of hooks on React's website. It can be counterintuitive at first. You might need to loop through components and have each one call their own `useCollection`. The code you shared is not valid React code.

**Comment by 345ml** [comment]
Thanks bro.

**Comment by binajmen** [comment]
I have the similar issue. I'm not quite sure to understand your suggestion @nandorojo. Could you please provide an example?

**Comment by nandorojo** [comment]
Please specify your use case and show what you've attempted.

**Comment by binajmen** [comment]
This is a simplified use case (with a NextJs context but the original question is still the same):
```js
export default function Album(props) {
  const { albumId } = router.query

  const method = useStoreState(state => state.basket.method)
  const basketSize = useStoreState(state => state.basket.size)
  const total = useStoreState(state => state.basket.total)
  const [product, setProduct] = React.useState<Product | null>(null)

  const album = useDocument(`albums/${albumId}`, { initialData: props.album })
  const tracks = useCollection(`tracks`, { initialData: props.tracks })

  return (...)
}

export const getServerSideProps = async ({ query }) => {
  const { albumId } = query

  const album = await admin.firestore().doc(`albums/${albumId}`).get()
  const trackRefs = album.tracks.map(trackId => {
    return admin.firestore().doc(`tracks/${trackId}`).get()
  })
  const _tracks = await Promise.all(trackRefs)
  const tracks = _tracks.reduce((acc, doc) => ([...acc, { ...doc.data(), id: doc.id }]), [])

  return {
    props: {
      album: album.data(),
      tracks: tracks
    }
  }
}
```

This `const tracks = useCollection(`tracks`, { initialData: props.tracks })` would work but the cache would wrongly assume that all the tracks has been already loaded.

**Comment by nandorojo** [comment]
I don't understand what you want to do / what the problem is.

Are you trying to refetch tracks when the page mounts? If so, pass `revalidateOnMount: true`

**Comment by sarimabbas** [comment]
Hi @nandorojo, thank you for creating this awesome library!

I'm having a similar problem to @345ml. Essentially, I want to create a logical "OR" query but using the "in" operator. 

Currently I am doing this using rxjs and observables:

```ts
const chunks = chunk(idsToCheckAgainst, 10);

// use RxFire to create observables out of each chunk 
const firebaseObservables = chunks.map((ck) => {
  return collectionData(filesCollection.where("parentId", "in", ck), "id");
});

// use RxJs to combine these observables into one observable
const combinedObservable = combineLatest(firebaseObservables).pipe(
  rxMap((all: any[]) => all.flat())
);
```

I want to do something similar with swr-firestore, basically watching an arbitrary number of queries and merging the results. It would be similar to the code @345ml posted:

```js
const data =  userIdsList.map((userIds) => {
  return useCollection(
    userIds.length > 0 ? 'users' : null,
    {
      where: ['id', 'in', userIds],
    }
  )
})
```

However, we know that we cannot put hooks inside loops. So would you have any suggestions for how to get around this? Thank you for your time!

**Comment by nandorojo** [comment]
It might make more sense to create a custom SWR book that loops through multiple `getCollection` calls, `Promise.all` those, and return that. This lib exports a `getCollection` function that lets you query a collection outside of a hook.

**Comment by sarimabbas** [comment]
Awesome, thank you for your quick response! I will investigate this further. Just to clarify, `getCollection` does not provide SWR-like caching benefits out of the box, right? I must use it in conjunction with `vercel/swr`? Thank you so much!
