### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by johnsheehan** [nandorojo/swr-firestore#99]
Currently can't install on the current version of Next.js due to react dependency version

**Comment by dhazeley** [comment]
If this is due to npm v7 blocking installs with mismatched peer dependencies, I think you can ignore that. I'm using React 17 right now with no issues and React 17 is a maintenance upgrade anyway with minimal breaking changes from v16.

**Comment by samipshah100** [comment]
I am using it on ```
"next": "^10.1.2",
    "next-redux-wrapper": "^6.0.2",
    "next-svgr": "^0.0.2",
    "notistack": "^1.0.5",
    "react": "17.0.0",
```

with no issues
